[env:weact_h743]
platform = ststm32
board = weact_mini_h743vitx
framework = stm32cube
upload_protocol = dfu
extra_scripts = pre:add_hardfloat.py

lib_archive = no
build_flags = 
    -O3
    -mcpu=cortex-m7
    -mfpu=fpv5-d16
    -mfloat-abi=hard
    -DUSE_HAL_DRIVER
    -DSTM32H743xx
    -DSTM32H7
    -I$PROJECT_DIR/lib/DaisySP/Source
    -I$PROJECT_DIR/lib/DaisySP/Source/Utility
    -I$PROJECT_DIR/src

lib_deps =
    baracodadailyhealthtech/tinyusb

board_build.ldscript = linker/STM32H743_WEACT.ld