name: Deploy Synth to GitHub Pages

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest
          actions-cache: true

      - name: Compilar WebAssembly
        run: |
          chmod +x build_wasm.sh
          ./build_wasm.sh

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'web' # Sobe toda a pasta 'web/' contendo o index.html principal e a pasta /midi/

      - name: Deploy para o GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
